# Generated by Django 5.0.3 on 2025-04-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_delete_phone_remove_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
